language: php
php:
    - 7.0
    - 7.1
before_script:
    - composer install --prefer-source

script: phpunit --coverage-text

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

language: php
